### ISSUE TITLE
After upgrade from 9.0.4~ynh6 to 9.1.0~ynh1 onlyoffice-docservice doesn't start

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/onlyoffice_ynh#194]
This is the error from `/var/log/onlyoffice/docservice.log`

```
Error: Configuration property "aiSettings.pluginDir" is not defined
    at Config.get (/snapshot/src/DocService/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiEngineWrapper.js)
    at Module._compile (pkg/prelude/bootstrap.js:1934:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiProxyHandler.js)
```

Any hint about where I would have to define that? On my server I can see `aiSettings` object in `/var/www/onlyoffice/config/default.json` but it doesn't have a `pluginDir` attribute.

Edit: After I added `pluginDir` attribute to that file I still couldn't start the service. Now, there is a new error:

```
TypeError: layout is not a function
    at /snapshot/src/Common/node_modules/log4js/lib/appenders/console.js:6:16
    at /snapshot/src/Common/node_modules/log4js/lib/log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (/snapshot/src/Common/node_modules/log4js/lib/log4js.js:42:21)
    at /snapshot/src/Common/node_modules/log4js/lib/clustering.js:25:28
    at Array.forEach (<anonymous>)
    at sendToListeners (/snapshot/src/Common/node_modules/log4js/lib/clustering.js:25:13)
    at Object.send (/snapshot/src/Common/node_modules/log4js/lib/clustering.js:91:7)
    at Logger._log (/snapshot/src/Common/node_modules/log4js/lib/logger.js:195:16)
    at Logger.log (/snapshot/src/Common/node_modules/log4js/lib/logger.js:155:12)
```

**Comment by nfalperen** [comment]
I came here to report this exact issue. I backed up the OnlyOffice application on my old server, uploaded the backup to the new server, and the system didn't work. The logs are as follows:
```
Error: Configuration property "aiSettings.pluginDir" is not defined
    at Config.get (/snapshot/src/DocService/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiEngineWrapper.js)
    at Module._compile (pkg/prelude/bootstrap.js:1934:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiProxyHandler.js)
```
```
Error: Configuration property "aiSettings.pluginDir" is not defined
    at Config.get (/snapshot/src/DocService/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiEngineWrapper.js)
    at Module._compile (pkg/prelude/bootstrap.js:1934:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/snapshot/src/DocService/sources/ai/aiProxyHandler.js)
```

Here's what I did to fix the problem: Upgrading the OnlyOffice application, performing a forced upgrade, adding logging records to the local.json file, adding aiSettings records to the local.json file, restarting services multiple times, restarting, upgrading, and force-upgrading over SSH, and completely deleting and reinstalling the application from a backup.
Considering YunoHost's philosophy, restoring an application from a backup shouldn't be this difficult. Two weeks ago, I abandoned my server because it was malfunctioning and bought a new one. I've been trying to restore the backups for 10 days. It's like trying to drag a boa constrictor by the tail into a cage. I'm struggling, changing many parts of many applications, but the snake keeps hitting me, hitting me left and right, coiling itself around me, and I'm trying superhumanly hard to do anything.
I've tried to solve many problems with artificial intelligence. I can send the output to anyone who's interested.

**Comment by djibux** [comment]
I have the same error that affects both `onlyoffice-docservice` and `onlyoffice-converter`.
Reverting to the pre-upgrade backup works as a workaround.

**Comment by zamentur** [comment]
SHould be fixed with the new 9.1.0~ynh2 version
